import { LARGE_BAT_HEALTH } from '../constants.js';

export const largeBatProto = {
    x: 0,
    y: 0,
    width: 45,
    height: 30,
    velocityX: 0,
    velocityY: 0,
    type: 'largeBat',
    state: 'idle',
    stateTimer: 0,
    originX: 0,
    originY: 0,
    patrolTargetX: 0,
    patrolTargetY: 0,
    patrolRange: 150,
    detectionRadius: 120,
    leashRadius: 180,
    chaseSpeed: 70.0,
    patrolSpeed: 40.0,
    flapTimer: 0,
    health: LARGE_BAT_HEALTH,
    randomMoveTimer: 0,
};
